//! RU/EN interface strings. Chassis/body/engine codes and years are NOT translated
//! (per the design) — only interface labels flip.

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Lang {
    Ru,
    En,
}

/// All interface strings for one language (from the handoff `STR` dict).
pub struct Dict {
    // Header / chrome
    pub title_sub: &'static str,
    pub interface: &'static str,
    pub connected: &'static str,
    pub adapter: &'static str,
    // Screen 1 — chassis
    pub series: &'static str,
    pub select_chassis: &'static str,
    pub e_series: &'static str,
    pub search_ph: &'static str,
    pub results: &'static str,
    pub open_hint: &'static str,
    pub lg_ready: &'static str,
    pub lg_partial: &'static str,
    pub lg_none: &'static str,
    // Screen 2 — ECU select
    pub select_ecu: &'static str,
    pub back: &'static str,       // "КУЗОВ" — back to chassis
    pub category: &'static str,
    pub all: &'static str,
    pub with_faults: &'static str,
    pub scan_all: &'static str,
    pub scanning: &'static str,
    pub col_ecu: &'static str,
    pub col_system: &'static str,
    pub col_bus: &'static str,
    pub col_addr: &'static str,
    pub col_status: &'static str,
    pub lg2_ok: &'static str,
    pub lg2_fault: &'static str,
    pub lg2_nolink: &'static str,
    pub st_nolink: &'static str,
    pub bus: &'static str,
    pub address: &'static str,
    pub part_no: &'static str,
    pub version: &'static str,
    pub dtc: &'static str,
    pub nolink_note: &'static str,
    pub pick_module: &'static str,
    pub connect: &'static str,
    pub connecting: &'static str,
    pub connect_failed: &'static str,
    pub retry: &'static str,
    pub close: &'static str,
    pub no_sgbd: &'static str,
    pub st_ready: &'static str,
    pub st_nosgbd: &'static str,
    pub err_no_response: &'static str,
    pub err_port_busy: &'static str,
    pub err_no_adapter: &'static str,
    pub err_generic: &'static str,
    pub read_faults: &'static str,
    pub clear_mem: &'static str,
    pub live_data: &'static str,
}

pub fn dict(lang: Lang) -> Dict {
    match lang {
        Lang::Ru => Dict {
            title_sub: "СИСТЕМА ДИАГНОСТИКИ",
            interface: "ИНТЕРФЕЙС",
            connected: "СВЯЗЬ ЕСТЬ",
            adapter: "АДАПТЕР",
            series: "СЕРИЯ",
            select_chassis: "ВЫБОР КУЗОВА",
            e_series: "E-СЕРИЯ",
            search_ph: "код или модель…",
            results: "НАЙДЕНО",
            open_hint: "2× — открыть",
            lg_ready: "ГОТОВ",
            lg_partial: "ЧАСТИЧНО",
            lg_none: "НЕТ",
            select_ecu: "ВЫБОР ЭБУ",
            back: "КУЗОВ",
            category: "КАТЕГОРИЯ",
            all: "ВСЕ",
            with_faults: "с ошибками",
            scan_all: "СКАН ВСЕХ",
            scanning: "СКАН",
            col_ecu: "ЭБУ",
            col_system: "СИСТЕМА",
            col_bus: "ШИНА",
            col_addr: "АДРЕС",
            col_status: "СТАТУС",
            lg2_ok: "НОРМА",
            lg2_fault: "ОШИБКИ",
            lg2_nolink: "НЕТ СВЯЗИ",
            st_nolink: "НЕТ СВЯЗИ",
            bus: "ШИНА",
            address: "АДРЕС",
            part_no: "НОМЕР ДЕТАЛИ",
            version: "ВЕРСИЯ ПО / HW",
            dtc: "КОДЫ ОШИБОК",
            nolink_note: "МОДУЛЬ НЕ ОТВЕЧАЕТ",
            pick_module: "ВЫБЕРИТЕ МОДУЛЬ",
            connect: "ПОДКЛЮЧИТЬСЯ",
            connecting: "ПОДКЛЮЧЕНИЕ…",
            connect_failed: "ОШИБКА ПОДКЛЮЧЕНИЯ",
            retry: "ПОВТОРИТЬ",
            close: "ЗАКРЫТЬ",
            no_sgbd: "SGBD для модуля не найден",
            st_ready: "ГОТОВ",
            st_nosgbd: "НЕТ SGBD",
            err_no_response: "Блок не отвечает",
            err_port_busy: "Порт COM3 занят другим приложением",
            err_no_adapter: "Адаптер не найден на COM3",
            err_generic: "Не удалось подключиться",
            read_faults: "ЧИТАТЬ ОШИБКИ",
            clear_mem: "СБРОС ПАМЯТИ",
            live_data: "ЖИВЫЕ ДАННЫЕ",
        },
        Lang::En => Dict {
            title_sub: "DIAGNOSTIC SYSTEM",
            interface: "INTERFACE",
            connected: "CONNECTED",
            adapter: "ADAPTER",
            series: "SERIES",
            select_chassis: "SELECT CHASSIS",
            e_series: "E-SERIES",
            search_ph: "code or model…",
            results: "RESULTS",
            open_hint: "2× to open",
            lg_ready: "READY",
            lg_partial: "PARTIAL",
            lg_none: "NONE",
            select_ecu: "SELECT ECU",
            back: "CHASSIS",
            category: "CATEGORY",
            all: "ALL",
            with_faults: "with faults",
            scan_all: "SCAN ALL",
            scanning: "SCAN",
            col_ecu: "ECU",
            col_system: "SYSTEM",
            col_bus: "BUS",
            col_addr: "ADDR",
            col_status: "STATUS",
            lg2_ok: "OK",
            lg2_fault: "FAULTS",
            lg2_nolink: "NO LINK",
            st_nolink: "NO LINK",
            bus: "BUS",
            address: "ADDRESS",
            part_no: "PART NUMBER",
            version: "SW / HW VERSION",
            dtc: "FAULT CODES",
            nolink_note: "MODULE NOT RESPONDING",
            pick_module: "SELECT A MODULE",
            connect: "CONNECT",
            connecting: "CONNECTING…",
            connect_failed: "CONNECTION FAILED",
            retry: "RETRY",
            close: "CLOSE",
            no_sgbd: "No SGBD found for this module",
            st_ready: "READY",
            st_nosgbd: "NO SGBD",
            err_no_response: "Module is not responding",
            err_port_busy: "COM3 is in use by another application",
            err_no_adapter: "Adapter not found on COM3",
            err_generic: "Could not connect",
            read_faults: "READ FAULTS",
            clear_mem: "CLEAR MEMORY",
            live_data: "LIVE DATA",
        },
    }
}
